### GET
### Получить все задачи
@baseUrl = http://localhost:5275

###
GET {{baseUrl}}/api/tasks

###
GET {{baseUrl}}/api/tasks?completed=true

###
GET {{baseUrl}}/api/tasks?completed=false

###
GET {{baseUrl}}/api/tasks/1

###
GET {{baseUrl}}/api/tasks/999

### POST

POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
    "title": "Задача из REST Client",
    "description": "Создана через файл .http",
    "priority": "High"
}

###
POST {{baseUrl}}/api/tasks
Content-Type: application/json

{
    "title": "",
    "description": "Описание без заголовка",
    "priority": "Normal"
}


### PUT
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json

{
    "title": "Изучить ASP.NET Core (обновлено)",
    "description": "Контроллеры, маршруты, DTO",
    "isCompleted": true,
    "priority": "High"
}
### PATCH
PATCH {{baseUrl}}/api/tasks/2/complete

### DELETE
DELETE {{baseUrl}}/api/tasks/4

### SEARCH
GET {{baseUrl}}/api/tasks/search?query=ASP

### HIGH PRIORITY
GET {{baseUrl}}/api/tasks/priority/High

### STATS
GET {{baseUrl}}/api/tasks/stats

### Sorted
GET {{baseUrl}}/api/tasks/sorted?by=priority&desc=false